### ISSUE TITLE
any scripts to generate zombie graphs from ftl_func_valid_ratios

### ISSUE THREAD

**Issue by rakeshpandit** [junhe/wiscsee#1]
Can you share any scripts you have used to generate zombie garphs from ftl_func_valid_ratios entries ? If yes it would be great you can add to repository. thanks,

**Comment by junhe** [comment]
There you go: https://github.com/junhe/wiscsee/tree/master/sides/plot-zombie-curve

I usually use R to plot. So, the script is in R. 

Each of dictionary in ftl_func_valid_ratios is a snapshot of the valid ratios. The script plots the last snapshot.

**Comment by rakeshpandit** [comment]
@junhe thank you for quick response.
