### ISSUE TITLE
Is it possible to calculate write amplification using this tool?

### ISSUE THREAD

**Issue by xxks-kkk** [junhe/wiscsee#10]
Hello,

I'm wondering if it is possible to calculate the write amplification using this tool?

Thanks!

**Comment by junhe** [comment]
Yes. It will allow you to get write amplification ratio for both hybrid FTL and page-mapping FTL.            

These are some of the parameters you may need to tune:

```
          'over_provisioning': [1.28], 
            'gc_high_ratio'    : [0.9], # when utilization reaches this number, it will trigger GC
            'gc_low_ratio'     : [0.0], # reaching this number will stop GC
```

**Comment by xxks-kkk** [comment]
Thanks for the info! I'll try it out and reopen the issue if I need further help! Thanks much!
