### ISSUE TITLE
query regarding SQLite microbenchmark used in study "The Unwritten Contract..."

### ISSUE THREAD

**Issue by rakeshpandit** [junhe/wiscsee#3]
The paper ("The Unwritten Contract...") mentions a microbenchmark developed by you folks to test SQLite workloads. Even though it seems simple to develop, it would be great if you can point me somewhere it is available for download or share.

My aim was to replicate the readings done for request scale... and others. Rather than re-writing I would rather use what you folks already used after checking it.

Thank you in advance.

**Comment by junhe** [comment]
The benchmark for SQLite is here https://github.com/junhe/wiscsee/tree/full-func/sqlitebench, in the full-func branch. I removed it from the master branch for simplicity of the code. 

You can find out how to use sqlbench in the unit tests https://github.com/junhe/wiscsee/blob/full-func/tests/test_sqlitebench.py

**Comment by rakeshpandit** [comment]
Thank you for quick answer.
